---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: olm
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/operator-framework/operator-lifecycle-manager.git
  ref:
    tag: v0.24.0
  ignore: |
    # exclude all
    /*
    # include chart
    !/deploy/chart/
