kind: ENC[AES256_GCM,data:agAl2k1I,iv:NCrqw2pZI/S1cRyp/spWG+HkHa/oQk/b/5Uvf3SD+IM=,tag:NZxwuVAeupgh+hxBsILhwA==,type:str]
ansible_user: ENC[AES256_GCM,data:nczfF0pF,iv:ytzyB/ohe1JginewEloE/gvQd23HACywVxuoih7Y/74=,tag:U5VweidjraKVVB8f5MECIw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:c0c+Jj9V,iv:9Z8PjZZTQnXEtW7LFd0dLbocQ0nGMFvogdK+LEgGnd0=,tag:Pf5yl6L1Sh53UCf4C/Ew2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hna22e7vukyxq8fru4xkeuq9c7lammpydmduhws2qg4ck47knglsl5760g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMUZsa2tSeWk0T0w1WE5P
            NGhENHF6R2pTYWgyZ3Vua3RJMkVvMC9jYWhZCm9vUUZXQXBjTFRkNlJJSi9lK0xO
            bG1HMGJpSHVwNEhXb24yNUxKbXB3eVUKLS0tIFFzZ2RpcFErd0lWcHJNR1RKYVoy
            bTdXbC84dmtFUjZVNGgyWkpMT3IvVE0KsCd85eqMhgHZ+s71GGvSSmOACII1baCH
            zeENLs3oFUeTg54VLLCYq8pCgazS9nAwmUlzMVuD6jFT9wFP4/Ou6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T22:38:56Z"
    mac: ENC[AES256_GCM,data:Kx0mSOVtqhvRFi644v7/h55VGltoOJl1ST9w4rd7cdcdRN3pp1f9LR9MiW9AM+9tcho1/nplurklyM0ez53JlF2fqXUQoPtQgtpEQJefLU6leDEpcivNWiSlYAkLbzuOV2pY1YbowOnFfozKq7SbMfMgXvEhnRv1mTD2jbFNkwU=,iv:qhEBD+i0y3950pzXVuSJrI/3/kGFlBO2NVz33llqBpg=,tag:Jlh7xei6fFCGSnfypB+lgg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
