kind: ENC[AES256_GCM,data:BMMfx8/8,iv:HBDCHq/TOzIOXu5P4xlFhSJaaK/nOJTIvM2VJ0Aqhlo=,tag:5KjNCSF72EQQQBm7HbLf3Q==,type:str]
ansible_user: ENC[AES256_GCM,data:QRi/Xl5a,iv:ZJwFLy/iuxm9R1yvnxZ8GrxFseHTd5XTyqmsmB0LjWI=,tag:TqnSwTj+UAxW3W/m6MJU3Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:rF6a1/V+,iv:m5nKqkNegtHxyQi50hvTzG48eRhk9wurTaTWnoJqzYU=,tag:mIrlil6/LBSmOISGCVgfyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hna22e7vukyxq8fru4xkeuq9c7lammpydmduhws2qg4ck47knglsl5760g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJakczYTR0RFczL2RNYS9q
            UVN4QnMyL0NBcjVLNDNRbGx4NkJDUDdPcXh3CktEMXlaS2JNcmNlSlVnM1lyTWNo
            bWovRm1Yays5UTc0bEFwUVRnazBvVEUKLS0tICtaMXlGK0d1dngwc1ZGZis5bjBy
            REJ0NUI5QllxSVBKdUM1VEVoNGJFWkEKMqab9PqKpgmzCh5g/y6v7ofDe1fBA2Sg
            slIdXOo1pF4ElkTrpPq5wNqvZn51n63OawYaHwwaCNp58i1gJOiyUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T20:11:53Z"
    mac: ENC[AES256_GCM,data:doWZeCJ5M0hxgymHvv6t2CD8sriGAOCj7WyvujuwxUhMFLoeurjwKjwnc3xMYBFx6avbHhoYUSjdSofD3cZyduXNtEutJ1tYgFthNkakL+9M7OjaDfML0tFBByySxrF5qOD6bTxafnjUPTfg/D8UtxXyIeCSKBE0jnrdxx9nHyY=,iv:UrqMNuHkIEhyZOpBTiSFMMzA1d0Wn+X9anabHBXHOyc=,tag:4n5LYhSOB8mfmwqZQobeBg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
