kind: ENC[AES256_GCM,data:8RSumu6V,iv:uRFX4RE7K5cHxCI1Sy/CwASTxRShEonQTrbQXMcJSZI=,tag:aJTL6aqUnllnqe1F/GTnvw==,type:str]
ansible_user: ENC[AES256_GCM,data:4N7OejqV,iv:CmscMEh2ihMM4t7fgG6qpbfi/BPITVGN3SVgw/rB/xs=,tag:AzncMW2kvSD0p4ZtYbeqkQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Cn6yJH16,iv:Hh9sH2Gng/NXtzN0b8TP3rYW1+yFrR+r0BikQBg/dno=,tag:LkIVcKOnjSHC8qvTnr40NA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hna22e7vukyxq8fru4xkeuq9c7lammpydmduhws2qg4ck47knglsl5760g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UXBKb2FwMC9pdUlaSWZh
            VG9weWgwUW9PV3FMVUZLcjdDSjB1MnpXUDBjCmkyaDllakNvUkxjMmV5VS9SejdR
            Q2toRitaTHNQQWZMbjNRVXQvdStVcUEKLS0tIHVkK1YxTVlPaFFkOWFoemxmVWR4
            b1lXU0dSWGVXMTRYNUx5WjdrZDBRbDAKbG2BIj2gTexdm2cN8LZHOcdl/8A8y3Rh
            sf0nxuWQIxIsBo8mag1jPrZPfDCGvCnxQaI6f4KcXYZvJiYa9iwJGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T18:27:13Z"
    mac: ENC[AES256_GCM,data:TAQ9vIG+gyjMYh4DjnZS4D/cyTXyzEx3OerLY5WHD4cx/qee2fx5ADTFCwzkpLiAml/KhNwhh/hs6Y/f4ZlYiOZ3RvTyAXL27b+3jIjcMzCZK/2a7+4IVJ1qJwhzfGDmYyL00hTC6+B6CJXZ5ET1AfMXh/SNbA+SEutUqzaC278=,iv:grNYuM+pKVnRmZDncwuaOMLXJcUAzH5oQrMIUnQZQgU=,tag:kutM6JPFzQ2nspz+dh0URQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
