---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: olm
  namespace: olm
spec:
  interval: 15m
  chart:
    spec:
      chart: ./deploy/chart
      sourceRef:
        kind: GitRepository
        name: olm
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    olm:
      nodeSelector:
        kubernetes.io/arch: amd64
    catalog:
      nodeSelector:
        kubernetes.io/arch: amd64
