---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-production"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "monitoring.${SECRET_DOMAIN}"
    - "*.monitoring.${SECRET_DOMAIN}"
    - "apps.${SECRET_DOMAIN}"
    - "*.apps.${SECRET_DOMAIN}"
    - "echo-server.${SECRET_DOMAIN}"
    - "ingress.${SECRET_DOMAIN}"
