apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:3/+i0wWSWCkZpBIWrUpj44zxxaO+T1oTZ2p6btP8K7K0v+Y/y62K9TvhHMxRG4oumoDazKQh0jNl7SIs,iv:bOp4cZKPbJnihQXLrScstHxK4xJI54DergP7EP39oFI=,tag:nBcJr1oely/x5ghymEgMcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hna22e7vukyxq8fru4xkeuq9c7lammpydmduhws2qg4ck47knglsl5760g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZEZVUkdEYTdxNmpMU2Uw
            MUdqa3k5aDAzNjBpSVNLWS9qR1JoTVMxang4CkFHdHlpU1Jvb2dQSTFEWDdkZFpN
            anhScHF5d01GcE1VNThvNWZRYXJUMlEKLS0tIDJRUG10VzIyZ3NiRVc4djBDcTRm
            MlhZSklOa21xRklwS3dBTDJFNWk4emMKc2UF328PO1fyj0RNT0fKDCi70iPcL9r5
            i/DmZvfqNfx/ucVkFLDmQH5e99VZH+CqaIdqgHSfpc9jzdrIFPtRTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T21:12:46Z"
    mac: ENC[AES256_GCM,data:c0ikPE/hMURqUcKbyx7NNIkYDC1a1pmBBaXx/O3CJqwM1vB4u3h5Xx/y5eGIWbWIAbERapiQKmHpVarv5vSS+DgfyuGKDr3uqCyxclX4r6jSRYAkn6zk52SCU9KRqx+f7zCfz8V1JUjVTaNPZgdl2cHWcndQY5meYtaDdJESxyY=,iv:Ny+lg4MzglBWDthltKXdbjLlP7+dXAf1poXe5jus8xU=,tag:Tx+OwMmm/b0zkhTYWTgNOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
