---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  METALLB_LB_RANGE: "10.10.1.200-10.10.1.210"
  METALLB_K8S_GATEWAY_ADDR: "10.10.1.200"
  METALLB_INGRESS_ADDR: "10.10.1.201"
  KUBE_VIP_ADDR: "10.10.1.254"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
