apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:wETLyAu0G+t3var7tQ7S7FwdFHDrtr1HZ3Yjf7UDykDZI9mN,iv:oph+z51/TeZTCIdGsksEQicHBwxDAUGbOzpR4QdqZ/U=,tag:vT2vpakGIqvmZQPZDWQdnQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:o+35hxE9A4JdyM+WZZ7OO5mZUGQCAX/obSJJdkKFxqEKRoudmDARfTdwjYYzPFhafRUdOeodxldBd/7GOnBz3Zli+xD/HFy2oxm3ROONYYb4nKZ0y350iUmw34DpHvSNh+NI2JYtghM7Gf+qbGROtfSyGfw+mYGsEzGbWoPYrINnRqbR9A/bRgsxrlV5cHYY6shF8cMgFWo3Nzz7W6hprdpJYqNGCy7nZ+xz5UIPxQ==,iv:GNaBskrcnYjv3XEtaCAKxXjP+BvVpE8KDOD94d3kuG8=,tag:a/8mT3gvafT0shdWHr/LXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hna22e7vukyxq8fru4xkeuq9c7lammpydmduhws2qg4ck47knglsl5760g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bjg0K1VsNE5FMVAyYkxD
            cTZwdnhuRkt3UjYrcHNYVjRpcHpHUS9QdWdjCmNraCt5bXR6SjlIOWdCeEh6S1Rm
            RlRjdi9vbEpOTG93Slo5UUNqL2NDNDAKLS0tIHZXS2h6Q1VETzB5ZkhQVlJCbTBa
            b3lQaS9UQjRKb0E4YnZra1FhODFxdW8Ksmirj2VnBZ412jHIwmTZ4skQRqxhFk7T
            XxsB3SP/oSXK3+1INyPYt1vYM3Tlv/vo/riHgLfc7lR6IN9Rw7WPkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T21:12:46Z"
    mac: ENC[AES256_GCM,data:w/yIka98iJUFCiTo2KYZ0X5AKOyaiNPZbOVt4rYmhevWBaShvYOD6A2bWkny6Z+F6nLLfbS+sDLDL4mekR9TxnE0PLum/z+vyC0mUveV9pPqfAMg4FUdn5wPSmpFRg+luTbPYw2u48Pc4fafq2ccObMKhbOnySGDd+3TbLb16p0=,iv:UvJ1i6nmAT8HFtWZa+kPiadMb6FyyPb8Thy597Qd2RA=,tag:LEjG8+O+H7nuwIeUGJy1Eg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
