apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:LKSo95HovbVE4sH+cnZyJAU9et0v9nEsbRHgtkXqPSkapQcN,iv:OFtBR37u3wWuyQNreGHtaeYB44ruu13AIulEHTOpZ/I=,tag:ihKpws64uzMwQsxXyyN4hw==,type:str]
    credentials.json: ENC[AES256_GCM,data:JFX/bPmheXyCnEb9rfN9B0MCYLktq+IRXjKHnF3ZnSyaUGf7VDquB3mfq/oh56CGzpncJx5VM8e6Tfwg20x2B4H4eHALmxugZeT92FmPiUDE4d9hYl9wOTrOPwMvtZLhu/kGTRwEaFSo2AyhlNGIWRZ6cFjdnfvn44hC/d6sa4beEaLcvWI8sL0Cxg/5NMF00zq5lMMJPzz1hO/Nt/LqzKdWa9wSel8+TkkyRTj7lw==,iv:myLKolQvuT4OWpu6F9kKhO5p7ekSFeQ4iXIPkZet+dw=,tag:XuftYZFTBII3rzIcFHjSpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hna22e7vukyxq8fru4xkeuq9c7lammpydmduhws2qg4ck47knglsl5760g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMWcxMWhjUXZpY2F3amF3
            c3ZMaE1aNFRscXlpQ3hZNmhCZEZZbFpLNXo4CmdualVRMEZzYng2czh4aHNBSnM3
            c01Cbkl0M2k5dkwrMkFlMDhhQ3RLRUUKLS0tIFFHaWhzci9zOG1VMHBjZTlJcjJE
            NTBEd0xzUlRvNllzMDhCUUcvbXJBUkEKLB2YdobYXiDSNI8NgBnwvmSPb8UEWJA1
            Ml/TgCeCYiqyo0d9nw58XmspHq1QvV9rKf3MIT8ZGKoNXmsxvVkIxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T22:38:56Z"
    mac: ENC[AES256_GCM,data:KEcSjtQg11qaoNS0y+KT5/hqwZw2P8yohSimaO9FqbihIb58pOCtulmZKn+9VviRH4XsrGmDT9B5bzyuVFY6Sar0FoPGeYCOh3ANDN76QR1SYfForjxC8TH3wOpNW91mIZV//qBoM+ZccYRwjpo8vDzKQ2zCWuxIzk3cHzZ9Hb0=,iv:qq2sxf8y3G1/QsJ2vi9BxxWtIKdpSaFJxsYYY0VK4Fc=,tag:a/aWagYzPehKYkZTMVNQig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
