apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:nqCnuwbYgowhE/JqkN/zpYyFGzgdU/Rfo2kImOERw5PXFIDd,iv:P+ff48FPEnScE7XarnQQXV20KtIxt07V4JWUDulR1Es=,tag:75oZz3jWs0kALeGB2Xjr5g==,type:str]
    credentials.json: ENC[AES256_GCM,data:QcUXaV5X2kcq+mwHjNvAqUuzl+2iqwLgN8qNyI9CzwLlLS+eIDYp96wyzzv2prb/KMy3gktShNgMGyeLdvKVb15QUeoI4QDq29pp7fh0mYmrruzVD+dGGhabNFzOAkHahMIFP10lyZyAYfCW1ZhR+D2lcTsI8I0EcaSee7NtsO3CIdG4PoW1NsoB14S0e3jB4j7cd7L1isUQfHk04u2Cfd5/VLMDzCYJ/Zgu/Gvdxw==,iv:ZYcKRxBZc5kY85Q1Rgw2zF3ysfGDYL6CqfxkAJYx5qc=,tag:J8tuIYO58kU2PHbfczuWiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hna22e7vukyxq8fru4xkeuq9c7lammpydmduhws2qg4ck47knglsl5760g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUjkzMVo5ZTJycy9YKzhW
            QW5CNndRNHZpRHJmdTdIb1d6WlhZc3dpUXdZCjdIUDBtc2QrKzJZNnlYS2ptRWlk
            c0x3V3ZRVzl5NUgzMWZ0VjZnYXlvMUUKLS0tIDR5M2luVlBtdG5LVnNoZWFRZUpt
            OWMxQVpjYlI1R1JVS1p6WWNvcEFQOVEKdETii6hdGMUbGeFtt+yXDJWt4qjqbwut
            La+mHCWBWChfxQswNnbuXh6hPWo+84BSk0JSVQ/dtOaPe56hLeMVrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T18:27:13Z"
    mac: ENC[AES256_GCM,data:T1QlKy+r1nVysDcp9qz11vSTo2KZl89m8j1GxHf90cTmkQ7S4jn+jdMPBZgSwXV/CGHkv5W79SxT9DdlQbv9N0CEJBRJCWMzSCNWYGYt+B/WU3HcdoG5vhAflngFCW8TdlKqUZubCH3ZtFiCgeg7bSdnnS0MtrPoHIKG+IESl68=,iv:AoEmFPLzh/U8pIIB7WLVSVs5nvEPPvP8tw1HXWI64bc=,tag:+WMdsMGcihihy98BSdlGoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
