apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:8Zz0qYFz1hh1pgL1K1fCxn7TGTqJu096W/9RemBcNVxAn4qi,iv:dPd7k8CqiRqVVm+eLyh3ZPUSoZhSFXEjyWNgAXAkjlA=,tag:Pg+X7LS/QrEFjfX1lZauPg==,type:str]
    credentials.json: ENC[AES256_GCM,data:zgCtmS9oV/1sgCdaDfSm9dY8pFgsqjYXta0fP1ErOvkBer+EB76aZ218WCB5Oy9lV2fO+FCbQkKgBqna3TQ6NzBVKNJS5cVScVCdmuRIBiHgXmyuCJSwIrgVTKPUoF8bp4Rvyt51u8QK8rI74yxLAx9cB02qTVcMi/eyRsWQuxccsMK74R+OCYb+wyoD9xsDjQiBlDEcKvMiypOqx4NPZwR3nO1ftUiz+EBtoIX6sQ==,iv:LG0pLdaYsWK9LCCy5MCTRb9oAxkOsf8ZRSu3WhW983k=,tag:Q8Omjs7AYURii71JSoG3rA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hna22e7vukyxq8fru4xkeuq9c7lammpydmduhws2qg4ck47knglsl5760g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bURlWUxSelFFdFROTlRw
            Rm1IZlg0TExBak1YcS8rME5PRlJ0WGNtT1VBCmlKdE5lZmhsbG9oY292bXN1WXdx
            RUtEOFRvTkdydlBDYmNMOUNNV1lCdVEKLS0tIEsrQm0wSHVNdkRubUpqY0NBRXVr
            bkp1SW5TQ0FyT20yZU12a05tTFVBYkUKCQNJ3RGtIxRRESq3rVVLuMRZ7ZVYQyKg
            D9YgNbIZtruSR4tZLg3+FPg6ulIGkECgCOPI441zAKP2AfjyqNDiag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T20:11:53Z"
    mac: ENC[AES256_GCM,data:GWPkzMIOGmvG3N54jmzgfTvoCC3pAiXHNaWg/1ZFqA1axYjUjIJGja84nb2FB8efUjM+5eSe+VxDLARLlJ+QYrgYEMHLTWzsu5dOiG8z0gVS9ZtJ/9Hh/XLIMyf1h/L5TxvGVo/6/CMWcZad0yFN/uhN+3z7qijIEObwWutA+EU=,iv:OUD0cJOV8zHH6pKcbi3dNbwRd9tNUGrC448wUCB15ik=,tag:80LJdtW7tAU78udLZBji7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
