---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
  namespace: networking
stringData:
  email: "${BOOTSTRAP_CLOUDFLARE_EMAIL}"
  api-key: "${BOOTSTRAP_CLOUDFLARE_APIKEY}"
  api-token: "${BOOTSTRAP_CLOUDFLARE_API_TOKEN}"
